# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfcae719c966ebf484881c3ce56e6543b546d1c96d963578aac18d5ffe83d3da20c0f693fe1e51d19b81351de3a9c64923e144bacf75cedcb6610990391a491c

test:
  secret_key_base: b2ecc2ae99116eac349873c92a209cf45250b174830f784335550b928c7405ef7da2fb13606c7176ab6d2b5508aa5cb0f9c8c4959ec449e9575456bee7b71894

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
