# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c5f01af59269f63e74d36d12e4c2a91e025e4b3b250eb1bbd2daf868daa346be1cf9199dc707f7029e9e294866cf4d9f3b46bdd76ddd0f8f3958197c62afdf6

test:
  secret_key_base: 954a772917c2ff555bb9ebc152a85fe4b3039cda72bf7a6ee3f3cef23f24cb7db0b2db2d8f426d55205401b4f9c14a5b2886eac15ea3631656df972c57d0600d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
