# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ce420432ab1c79ad21886a00683ed650b393bb93b5afa2229087d3274dba9fc8c2e82a42e9df7b21afe7f67c7801ef51aef08be324a61fa6d5ffa2d710fe83d

test:
  secret_key_base: edb887a85a85b00b7ce0ee790441c1a0425738bed8c4ab8ec3149ec4199f5cd538234b2014201f0da2b9c8cee8784d4a715c00496a9f8e4c477cb6905d54cd67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
